# 
# GitHub Actions workflow.
#
# Automatically deploys the "animal" microservice on push.
#

name: Deploy Animals

on:
  push:
    branches: 
      - main
    paths:
      - 'services/animals/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      #
      # Builds the Docker image.
      #
      - name: Build
        run:  | 
          cd services
          ../scripts/build_image.sh animals

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run:  |
          cd services
          ../scripts/push_image.sh animals

      - name: 'Az CLI login'
        uses: Azure/login@v1
        with:
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            
      - name: 'Deploy Container App'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Deploy"
            az containerapp update -n animal-aca -g DefaultResourceGroup-EUS -i ${{ secrets.CONTAINER_REGISTRY }}/animals:${{ github.sha }} --registry-login-server ${{ secrets.CONTAINER_REGISTRY }} --registry-username  ${{ secrets.REGISTRY_UN }} --registry-password ${{ secrets.REGISTRY_PW }} --debug


