# 
# GitHub Actions workflow.
#
# Automatically deploys the "animal" microservice on push.
#

name: Deploy Animals

on:
  push:
    branches: 
      - main
    paths:
      - 'services/animals/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      #
      # Builds the Docker image.
      #
      - name: Build
        run:  | 
          cd services
          ../scripts/build_image.sh animals

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run:  |
          cd services
          ../scripts/push_image.sh animals

      - name: 'Az CLI login'
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          imageToDeploy: ${{ secrets.CONTAINER_REGISTRY }}/animals:${{ github.sha }}
          containerAppName: animal-aca
          containerAppEnvironment: managedEnvironment-DefaultResource-b8bf
          resourceGroup: DefaultResourceGroup-EUS

