# 
# GitHub Actions workflow.
#
# Automatically deploys the microservice on a push to the main branch
#

name: Build & Publish & Push the queue processor Container App 

# on:
#   push:
#     branches: 
#       - main
#     paths:
#       - 'services/queueprocessor/**'
#   workflow_dispatch:

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'services/queueprocessor/**'      


jobs:

  call-build-deploy-container-app:
    uses: ./.github/workflows/_build_deploy_containerapp_code.yml
    with:
      app-name: queueprocessor
    secrets:
      container_registry: ${{ secrets.container_registry }}
      container_registry_id: ${{ secrets.container_registry_id }}
      container_registry_pw: ${{ secrets.container_registry_pw }}
      azure_credentials: ${{ secrets.azure_credentials }}
