# 
# GitHub Actions workflow.
#
# Automatically deploys the "feapp" microservice on push.
#

name: Deploy photos App

on:
  push:
    branches: 
      - main
    paths:
      - 'services/photos/**'
  workflow_dispatch:

jobs:

  call-build-deploy-container-app:
    uses: ./.github/workflows/build_push_container_app.yml
    with:
      app-name: photos
    secrets:
      container_registry: ${{ secrets.container_registry }}
      registry_id: ${{ secrets.registry_id }}
      registry_pw: ${{ secrets.registry_pw }}
      azure_credentials: ${{ secrets.azure_credentials }}
