# 
# GitHub Actions workflow.
#

name: creae or update the photos container app

on:
  workflow_dispatch:

jobs:

  call-build-deploy-container-app:
    uses: ./.github/workflows/provision_update_workflow.yml
    with:
      containerapp_name: photos
      containerapp_environment_rg: ltl-aca-rg
      containerapp_environment_name: ltl-aca-env
      container_registry_image: photos:94f8993dc1d12c00b58004e0c1a3235edbc4cf51

    secrets:
      container_registry: ${{ secrets.container_registry }}
      container_registry_id: ${{ secrets.container_registry_id }}
      container_registry_pw: ${{ secrets.container_registry_pw }}
      azure_credentials: ${{ secrets.azure_credentials }}
      azure_storagetable_connectionstring: ${{ secrets.azure_storagetable_connectionstring }}
      aad_client_id: ${{ secrets.aad_client_id }}
      aad_client_secret: ${{ secrets.aad_client_secret }}
      google_client_secret_base64: ${{ secrets.google_client_secret_base64 }}
      tenant_id: ${{ secrets.tenant_id }}
      subscription_id: ${{ secrets.subscription_id }}
